#!/bin/bash -e

#DEBHELPER#

MESON_VERSION="#ENV.MESON_VERSION#"

installMeson() {
  pip3 install --no-warn-script-location meson=="${MESON_VERSION}"
}

if [ "$1" = "configure" ]; then
  installMeson
fi
