#!/bin/bash -e

#DEBHELPER#

installMeson() {
  pip3 install --upgrade --no-index --no-warn-script-location \
    --find-links=/var/lib/meson-installer \
    meson
}

if [ "$1" = "configure" ]; then
  installMeson
fi
