#!/bin/bash -e

#DEBHELPER#

packageVersion() {
  dpkg-query --show --showformat='${Version}' meson-installer
}

installMeson() {
  local packageVersion=$(packageVersion)
  local mesonVersion=${packageVersion%~*}
  pip3 install --no-warn-script-location meson==${mesonVersion}
}

if [ "$1" = "configure" ]; then
  installMeson
fi
