name: Create release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_call:
    inputs:
      upstream_version:
        description: The upstream version
        required: false
        type: string
  workflow_dispatch:
    inputs:
      upstream_version:
        description: The upstream version
        required: false
        type: string

permissions:
  contents: write

env:
  GIT_USER_NAME: Fra Bot
  GIT_USER_EMAIL: fragoibot@gmail.com
  EXCLUDE_FILES: '.github/**'
  DEBPACKAGE: meson-installer
  DEBDIST: focal

jobs:

  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.exportVersion.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: fragoi/bash-actions@main
      - name: Create release
        run: |
          debNewVersion "${{ inputs.upstream_version }}"
      - name: Export version
        id: exportVersion
        run: |
          output version=$(debChangelogVersion)

  notify-ppa:
    needs: [release]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: fragoi/bash-actions@main
      - name: Notify PPA repository
        env:
          VERSION: ${{ needs.release.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.PPA_TOKEN }}
        run: |
          repositoryDispatch fraorg/meson-installer-ppa \
            -f event_type=new_version \
            -f client_payload[version]="$VERSION"
