name: Build and release PPA

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  DEBPACKAGE: meson-installer
  PPA: ppa:fragoi/test

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: fragoi/bash-actions@main

      - name: Download source
        run: |
          downloadTag $GITHUB_REPOSITORY $GITHUB_REF_NAME

      - name: Build source package
        uses: fragoi/debuild-action@main
        with:
          ppa: ${{ env.PPA }}

      - if: ${{ vars.DEBSIGN }}
        name: Upload source package
        uses: fragoi/debsign-action@main
        with:
          ppa: ${{ env.PPA }}
          gpg_key: ${{ secrets.GPG_KEY }}
          gpg_pass: ${{ secrets.GPG_PASS }}
          ssh_key: ${{ secrets.SSH_PASS }}
          ssh_pass: ${{ secrets.SSH_PASS }}
